### ISSUE TITLE
wit-deps creating lots of GH Actions caches

### ISSUE THREAD

**Issue by tschneidereit** [bytecodealliance/wit-deps#60]
I just noticed that this project is creating a huge amount of Actions caches: https://github.com/bytecodealliance/wit-deps/actions/caches. Unfortunately this leads to also using a large amount of disk space, and overflowing out quotas on that. (16GB+ vs 10GB allowance)

@rvolosatovs is that something you could look into and ideally address?

**Comment by rvolosatovs** [comment]
Thanks for the report @tschneidereit , I was not aware there was a quota - the simple quick fix is to just remove them all, if that's something that should be fixed ASAP. There's an external cache in place anyway, GH one is really just an optimization

There should be a way to clean-up old cashes, though, I'll research next week

**Comment by rvolosatovs** [comment]
Looking at GitHub docs:
> GitHub will remove any cache entries that have not been accessed in over 7 days. There is no limit on the number of caches you can store, but the total size of all caches in a repository is limited to 10 GB. Once a repository has reached its maximum cache storage, the cache eviction policy will create space by deleting the oldest caches in the repository.
>
> If you exceed the limit, GitHub will save the new cache but will begin evicting caches until the total size is less than the repository limit. The cache eviction process may cause cache thrashing, where caches are created and deleted at a high frequency. To reduce this, you can review the caches for a repository and take corrective steps, such as removing caching from specific workflows. For more information, see "Managing caches."

So it seems that GitHub will simply delete the old caches eventually. What problem are we actually solving here?
Is the quota in this repository anyhow affecting other repositories in the org? Does cost us any money to be over quota?

**Comment by ricochet** [comment]
Reading through the GitHub docs, it looks like caches are free and the caches here will be automatically evicted. Wasmtime also consistently stays at the 10GB limit.

I don't think there's an action to take here. @tschneidereit if you're seeing something that's causing an issue, we can definitely dig in more.

**Comment by tschneidereit** [comment]
Ok, if the way wit-deps is using caches is working as intended, then I agree that this all seems fine. The large number of caches makes me suspect that we might not make the best use of them though: my guess would be that we have a pretty low cache hit rate?

**Comment by rvolosatovs** [comment]
> Ok, if the way wit-deps is using caches is working as intended, then I agree that this all seems fine. The large number of caches makes me suspect that we might not make the best use of them though: my guess would be that we have a pretty low cache hit rate?

It is working as intended indeed, it's just quite different from what you would expect if you were to cache plain `cargo` build artifacts, for example.

Each of the entries represents an entry in content-addressable Nix store.
For example, one of the entries represents workspace dependency build artifacts produced by https://crane.dev/API.html#cranelibbuilddepsonly
Whenever the cargo dependency set changes  or anything else that affects this build, e.g. cargo used to build it or a C compiler used to cross-compile particular target etc changes, this derivation would be rebuilt and would produce a new cache entry.
Each build is deterministic and reproducible, and that expands to also e.g. the compiler used, which is also reproducibly-built (just not by us, in overwhelming majority of cases). What this means also is that we can make assertions about tools used to build the project, since the whole state of the "world" is locked in `flake.lock`, which is, essentially, an SBOM.

If you're interested in learning more, you could try something like:
```
nix show-derivation 'github:bytecodealliance/wit-deps#packages.x86_64-linux.wit-deps-aarch64-unknown-linux-musl'
```
This would give you the exact set of *paths* in the Nix store (which the cache entries represent) used to build the binary on x86_64-linux for aarch64-unknown-linux-musl

The cache entries themselves are created by https://github.com/DeterminateSystems/magic-nix-cache-action

**Comment by tschneidereit** [comment]
Thank you for the detailed explanation, @rvolosatovs! <3 I think this covers everything, so I'll go ahead and close this
